print()
print("Welcome to CovLet!")
print()
print("A couple quick notes, any time you see '(c)' it means your response should be capitalized")
print("And CovLet doesnt save or store any information you give us and everything is completely confidential")
print("Once you are ready to start just begin answering the questions!")
print()
name1 = input("What is your first and last name (c): ")
address = input("What is your address: ")
postalCode = input("What is your postal code: ")
choice = input("Are you applying for a part time or full time job: ")
choice1 = input("What level of job are you applying for (example: entry, intermediate, etc): ")
choice2 = input("What would your job title be (examples: manager, cashier, etc): ")
choice3 = input("What is your first name(c): ")
choice4 = input("What is a good skill you have related to the job (example: coding, skateboarding, etc): ")
goodAt = input("What is a good quality you have (examples: team player, problem solver, etc): ")
work = input("Where was the last place you worked(c): ")
print()
print(name1)
print(address)
print(postalCode)
print("Dear hiring manager, My name is", choice3, "and I am applying for an", choice1, "level", choice, "job as a", choice2, "and I think I would be a great fit for this job because I have a good understanding of", choice4, "I am a great", goodAt, "and I think my resume demonstrates this well. As you will see in my resume, I have experience working at", work, "and I'm sure if you looked into what I did there, you would hear nothing but the best.")
